/// Authoritative list of parameters in order
pub const PARAMETERS: &[Parameter] = &[
    Parameter::Master(MasterParameter::Volume),
    Parameter::Master(MasterParameter::Frequency),
    Parameter::Operator(0, OperatorParameter::Volume),
    Parameter::Operator(0, OperatorParameter::Active),
    Parameter::Operator(0, OperatorParameter::MixOut),
    Parameter::Operator(0, OperatorParameter::Panning),
    Parameter::Operator(0, OperatorParameter::WaveType),
    Parameter::Operator(0, OperatorParameter::Feedback),
    Parameter::Operator(0, OperatorParameter::FrequencyRatio),
    Parameter::Operator(0, OperatorParameter::FrequencyFree),
    Parameter::Operator(0, OperatorParameter::FrequencyFine),
    Parameter::Operator(0, OperatorParameter::AttackDuration),
    // Parameter::Operator(0, OperatorParameter::AttackValue),
    Parameter::Operator(0, OperatorParameter::DecayDuration),
    Parameter::Operator(0, OperatorParameter::DecayValue),
    Parameter::Operator(0, OperatorParameter::ReleaseDuration),
    Parameter::Operator(1, OperatorParameter::Volume),
    Parameter::Operator(1, OperatorParameter::Active),
    Parameter::Operator(1, OperatorParameter::MixOut),
    Parameter::Operator(1, OperatorParameter::Panning),
    Parameter::Operator(1, OperatorParameter::WaveType),
    Parameter::Operator(1, OperatorParameter::ModTargets),
    Parameter::Operator(1, OperatorParameter::ModOut),
    Parameter::Operator(1, OperatorParameter::Feedback),
    Parameter::Operator(1, OperatorParameter::FrequencyRatio),
    Parameter::Operator(1, OperatorParameter::FrequencyFree),
    Parameter::Operator(1, OperatorParameter::FrequencyFine),
    Parameter::Operator(1, OperatorParameter::AttackDuration),
    // Parameter::Operator(1, OperatorParameter::AttackValue),
    Parameter::Operator(1, OperatorParameter::DecayDuration),
    Parameter::Operator(1, OperatorParameter::DecayValue),
    Parameter::Operator(1, OperatorParameter::ReleaseDuration),
    Parameter::Operator(2, OperatorParameter::Volume),
    Parameter::Operator(2, OperatorParameter::Active),
    Parameter::Operator(2, OperatorParameter::MixOut),
    Parameter::Operator(2, OperatorParameter::Panning),
    Parameter::Operator(2, OperatorParameter::WaveType),
    Parameter::Operator(2, OperatorParameter::ModTargets),
    Parameter::Operator(2, OperatorParameter::ModOut),
    Parameter::Operator(2, OperatorParameter::Feedback),
    Parameter::Operator(2, OperatorParameter::FrequencyRatio),
    Parameter::Operator(2, OperatorParameter::FrequencyFree),
    Parameter::Operator(2, OperatorParameter::FrequencyFine),
    Parameter::Operator(2, OperatorParameter::AttackDuration),
    // Parameter::Operator(2, OperatorParameter::AttackValue),
    Parameter::Operator(2, OperatorParameter::DecayDuration),
    Parameter::Operator(2, OperatorParameter::DecayValue),
    Parameter::Operator(2, OperatorParameter::ReleaseDuration),
    Parameter::Operator(3, OperatorParameter::Volume),
    Parameter::Operator(3, OperatorParameter::Active),
    Parameter::Operator(3, OperatorParameter::MixOut),
    Parameter::Operator(3, OperatorParameter::Panning),
    Parameter::Operator(3, OperatorParameter::WaveType),
    Parameter::Operator(3, OperatorParameter::ModTargets),
    Parameter::Operator(3, OperatorParameter::ModOut),
    Parameter::Operator(3, OperatorParameter::Feedback),
    Parameter::Operator(3, OperatorParameter::FrequencyRatio),
    Parameter::Operator(3, OperatorParameter::FrequencyFree),
    Parameter::Operator(3, OperatorParameter::FrequencyFine),
    Parameter::Operator(3, OperatorParameter::AttackDuration),
    // Parameter::Operator(3, OperatorParameter::AttackValue),
    Parameter::Operator(3, OperatorParameter::DecayDuration),
    Parameter::Operator(3, OperatorParameter::DecayValue),
    Parameter::Operator(3, OperatorParameter::ReleaseDuration),
    Parameter::Lfo(0, LfoParameter::Target),
    Parameter::Lfo(0, LfoParameter::BpmSync),
    Parameter::Lfo(0, LfoParameter::FrequencyRatio),
    Parameter::Lfo(0, LfoParameter::FrequencyFree),
    Parameter::Lfo(0, LfoParameter::Mode),
    Parameter::Lfo(0, LfoParameter::Shape),
    Parameter::Lfo(0, LfoParameter::Amount),
    Parameter::Lfo(0, LfoParameter::Active),
    Parameter::Lfo(1, LfoParameter::Target),
    Parameter::Lfo(1, LfoParameter::BpmSync),
    Parameter::Lfo(1, LfoParameter::FrequencyRatio),
    Parameter::Lfo(1, LfoParameter::FrequencyFree),
    Parameter::Lfo(1, LfoParameter::Mode),
    Parameter::Lfo(1, LfoParameter::Shape),
    Parameter::Lfo(1, LfoParameter::Amount),
    Parameter::Lfo(1, LfoParameter::Active),
    Parameter::Lfo(2, LfoParameter::Target),
    Parameter::Lfo(2, LfoParameter::BpmSync),
    Parameter::Lfo(2, LfoParameter::FrequencyRatio),
    Parameter::Lfo(2, LfoParameter::FrequencyFree),
    Parameter::Lfo(2, LfoParameter::Mode),
    Parameter::Lfo(2, LfoParameter::Shape),
    Parameter::Lfo(2, LfoParameter::Amount),
    Parameter::Lfo(2, LfoParameter::Active),
    Parameter::Lfo(3, LfoParameter::Target),
    Parameter::Lfo(3, LfoParameter::BpmSync),
    Parameter::Lfo(3, LfoParameter::FrequencyRatio),
    Parameter::Lfo(3, LfoParameter::FrequencyFree),
    Parameter::Lfo(3, LfoParameter::Mode),
    Parameter::Lfo(3, LfoParameter::Shape),
    Parameter::Lfo(3, LfoParameter::Amount),
    Parameter::Lfo(3, LfoParameter::Active),
];

/// Parameter enum used to abstract over parameter indices
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum Parameter {
    /// Only used in LFO targetting
    None,
    Master(MasterParameter),
    Operator(u8, OperatorParameter),
    Lfo(u8, LfoParameter),
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum MasterParameter {
    Volume,
    Frequency,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum OperatorParameter {
    Volume,
    Active,
    MixOut,
    Panning,
    WaveType,
    ModTargets,
    ModOut,
    Feedback,
    FrequencyRatio,
    FrequencyFree,
    FrequencyFine,
    AttackDuration,
    DecayDuration,
    DecayValue,
    ReleaseDuration,
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum LfoParameter {
    Target,
    BpmSync,
    FrequencyRatio,
    FrequencyFree,
    Mode,
    Shape,
    Amount,
    Active,
}
